import {
  faDumbbell,
  faCartShopping,
  faGraduationCap,
  faHouse,
  faPeopleGroup,
  faPersonSwimming,
  faPersonWalking,
  faPersonRunning,
  faCar,
  faList,
  faMusic,
  faDog,
  faCat,
  faPaw,
  faPills,
  faCoins,
  faSun,
  faHeart,
  faStar,
  faScissors,
  faSailboat,
  faFootball,
  faBasketball,
  faSoccerBall,
  faFish,
  faUtensils,
  faTruck,
  faGift,
  faTableTennisPaddleBall,
  faBaseballBatBall,
  faClock,
  faCalendarDay,
} from "@fortawesome/free-solid-svg-icons";

export const groupIcons = {
  list: faList,
  dumbbell: faDumbbell,
  cartShopping: faCartShopping,
  graduationCap: faGraduationCap,
  house: faHouse,
  peopleGroup: faPeopleGroup,
  personSwimming: faPersonSwimming,
  personRunning: faPersonRunning,
  car: faCar,
  music: faMusic,
  fish: faFish,
  dog: faDog,
  cat: faCat,
  paw: faPaw,
  pills: faPills,
  coins: faCoins,
  sun: faSun,
  heart: faHeart,
  star: faStar,
  scissors: faScissors,
  sailboat: faSailboat,
  soccerBall: faSoccerBall,
  football: faFootball,
  basketball: faBasketball,
  baseballBatBall: faBaseballBatBall,
  tableTennisPaddleBall: faTableTennisPaddleBall,
  utensils: faUtensils,
  gift: faGift,
  calendarDay: faCalendarDay,
  clock: faClock,
};
